### ISSUE TITLE
那么早就说用Angular，会不会给人一种

### ISSUE THREAD

**Issue by water-vapor** [iamacewhite/teamform-seed#3]

**Comment by iamacewhite** [comment]
拉出去续了

**Comment by hjiaa** [comment]
-1s

**Comment by water-vapor** [comment]
这个github collaboration, 我们有几年就用的是github的issue，旁边放着angular的文档。坠痛苦的，就是提issue的时候，刚提出来就被close了，写的comment一下子就。。。然后还要去申请reopen，这就是github操作中最痛苦的。

**Comment by iamacewhite** [comment]
看你这么怨念我就重开吧
